# Generated by Django 6.0 on 2026-01-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TAMANO', 'Tamaño'), ('SABOR', 'sabor'), ('DECORACION', 'Decoración'), ('OTRO', 'otro')], max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'VarianteProdcuto',
                'verbose_name_plural': 'variantesproducto',
                'ordering': ['tipo', 'nombre'],
                'unique_together': {('tipo', 'nombre')},
            },
        ),
    ]
