# Generated by Django 6.0 on 2026-04-25 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_varianteproducto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varianteproducto',
            options={'ordering': ['tipo', 'nombre'], 'verbose_name': 'Variante Producto', 'verbose_name_plural': 'Variantes Producto'},
        ),
        migrations.RenameIndex(
            model_name='producto',
            new_name='producto_nombre_38c699_idx',
            old_name='products_pr_nombre_203300_idx',
        ),
        migrations.RenameIndex(
            model_name='producto',
            new_name='producto_activo_63f8df_idx',
            old_name='products_pr_activo_5016eb_idx',
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
        migrations.AlterModelTable(
            name='varianteproducto',
            table='variante_producto',
        ),
    ]
