# Generated by Django 6.0 on 2026-01-17 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0003_varianteproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionPersonalizadaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_personalizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='orders.pedidopersonalizado')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opciones_pedido', to='products.varianteproducto')),
            ],
            options={
                'verbose_name': 'Opcion personalizada del pedido',
                'verbose_name_plural': 'Opciones personalizadas del pedido',
                'db_table': 'opcion_personalizada_pedido',
                'unique_together': {('detalle_personalizacion', 'variante')},
            },
        ),
    ]
