# Generated by Django 6.0 on 2026-04-25 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_opcionpersonalizadapedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'verbose_name': 'Detalle Pedido', 'verbose_name_plural': 'Detalle Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedidopersonalizado',
            options={'verbose_name': 'Pedido Personalizado', 'verbose_name_plural': 'Pedidos Personalizados'},
        ),
        migrations.AlterModelTable(
            name='detallepedido',
            table='detalle_pedido',
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='pedido',
        ),
        migrations.AlterModelTable(
            name='pedidopersonalizado',
            table='pedido_personalizado',
        ),
    ]
