# Generated by Django 6.0 on 2025-12-28 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalusuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
    ]
