# Generated by Django 6.0 on 2026-09-15 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_historicalusuario_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalusuario',
            old_name='esta_activo',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='historicalusuario',
            old_name='es_staff',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='historicalusuario',
            old_name='es_superusuario',
            new_name='is_superuser',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='esta_activo',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='es_staff',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='es_superusuario',
            new_name='is_superuser',
        ),
    ]
