# Generated by Django 6.0 on 2026-04-25 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'ordering': ['nombre'], 'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
        migrations.AlterModelOptions(
            name='itemproduccion',
            options={'verbose_name': 'Item de Producccion', 'verbose_name_plural': 'Items de Produccion'},
        ),
        migrations.AlterModelOptions(
            name='receta',
            options={'verbose_name': 'receta', 'verbose_name_plural': 'recetas'},
        ),
        migrations.AlterModelOptions(
            name='recetainsumo',
            options={'verbose_name': 'Receta Insumo', 'verbose_name_plural': 'Receta Insumos'},
        ),
        migrations.AlterModelTable(
            name='insumo',
            table='insumo',
        ),
        migrations.AlterModelTable(
            name='itemproduccion',
            table='item_produccion',
        ),
        migrations.AlterModelTable(
            name='receta',
            table='receta',
        ),
        migrations.AlterModelTable(
            name='recetainsumo',
            table='receta_insumo',
        ),
    ]
